#Outputted the list students
puts "The students of Villians Academy"
puts "-------------"
puts "Dr. Hannibal Lector"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
# Unlike puts, print does not add new character so have use escape character (\n) 
print "Overall, we have "
print "11"
puts " great students"
